# Site settings
title: Lessandro Z. Ugulino # site title
description: >- # site description
  My personal site.
lang: en-US # default lang
timezone: Australia/Sydney # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/lezampieri/whoami # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Lessandro Z. Ugulino # author name
  bio: >- # tell to the world
    Curious for as long as I can remember, loving automate things, working as <strong>Site Reliability Engineer</strong> at <a href="https://www.ticketek.com.au/" target="_blank">Ticketek </a>and always looking for a good coffee.<br>Want to have a chat? Contact me: <br><a href="https://www.linkedin.com/in/lezampieri/" target="_blank" rel="noopener">@linkedin</a><br><a href="mailto:lessandro.ugulino@outlook.com">@email</a><br><a href="https://github.com/lezampieri/whoami" target="_blank" rel="noopener">@github</a>.
  username: username # author username
  github: lezampieri
  #twitter: twitter_username
  #facebook: facebook_username
  email: lessandro.ugulino@outlook.com # your contact adress
  avatar: /assets/img/avatar.jpeg # change with your own avatar
#bundle exec jekyll serve

certification:
  MsAzure: /assets/img/MSAzure.png
  AWSPro: /assets/img/AwsPro.png
  AWSAss: /assets/img/AWSAss.png
  MCSA16: /assets/img/MCSA16.png
  MCSA17: /assets/img/MCSA17.png
  MCSA12: /assets/img/MCSA12.png
  Ex417: /assets/img/417.png
  Ex410: /assets/img/410.png
  ITIL: /assets/img/ITIL.png

# Url settings
#url: "https://klise.now.sh"
baseurl: ""
permalink: /:title/
google_analytics: UA-175473224-1
fb_appid:

# Collection setting
collections:
  posts:
    output: false

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
